import { m } from "@/paraglide/messages"
import {
	CHARACTER_ENUM_FIELDS,
	CHARACTER_TAG_FIELDS,
	EMOTION_FIELDS,
} from "@/constants/mind"
import type {
	ArchetypePreset,
	ConfigField,
	ConfigSectionDef,
} from "@/types/config"

const STT_ENGINES = ["WHISPER", "MOONSHINE", "ZIPFORMER"] as const
const LLM_ENGINES = ["OLLAMA", "OPENAI_COMPATIBLE"] as const
const TTS_ENGINES = ["KOKORO"] as const
const WAKE_WORD_ENGINES = ["KWS"] as const
const PLAYBACK_ENGINES = ["SOX", "PLAY-SOUND"] as const
const MQTT_PROTOCOLS = ["mqtt", "mqtts", "ws", "wss"] as const
const PROVIDERS = ["cpu", "cuda", "coreml"] as const

const PERSONA_FIELDS: ConfigField[] = [
	{
		key: "name",
		label: m.config_field_character_name,
		kind: "text",
		hint: m.config_hint_character_name,
	},
	...CHARACTER_ENUM_FIELDS.map(
		(f): ConfigField => ({
			key: f.key,
			label: f.label,
			kind: "select",
			options: f.values,
		}),
	),
	{ key: "language", label: m.config_field_primary_language, kind: "text" },
	{
		key: "culturalBackground",
		label: m.config_field_cultural_background,
		kind: "text",
	},
	...CHARACTER_TAG_FIELDS.map(
		(f): ConfigField => ({ key: f.key, label: f.label, kind: "tags" }),
	),
]

const EMOTION_RADAR_FIELDS: ConfigField[] = EMOTION_FIELDS.map(
	(f): ConfigField => ({
		key: f.key,
		label: f.label,
		kind: "slider",
		min: -1,
		max: 1,
		step: 0.05,
	}),
)

export const CONFIG_SECTIONS: ConfigSectionDef[] = [
	{
		id: "identity",
		label: m.config_section_identity,
		icon: "identity",
		group: "personality",
		kind: "fields",
		source: "domia",
		description: m.config_section_identity_desc,
		fields: [
			{
				key: "name",
				label: m.config_field_domia_name,
				kind: "text",
				hint: m.config_hint_domia_name,
			},
		],
	},
	{
		id: "character",
		label: m.config_section_character,
		icon: "user",
		group: "personality",
		kind: "fields",
		description: m.config_section_character_desc,
		fields: PERSONA_FIELDS,
	},
	{
		id: "emotion",
		label: m.config_section_emotion,
		icon: "heart",
		group: "personality",
		kind: "radar",
		description: m.config_section_emotion_desc,
		fields: EMOTION_RADAR_FIELDS,
	},
	{
		id: "tts",
		label: m.config_section_tts,
		icon: "audio",
		group: "engines",
		kind: "fields",
		description: m.config_section_tts_desc,
		fields: [
			{
				key: "engine",
				label: m.config_field_engine,
				kind: "select",
				options: TTS_ENGINES,
			},
			{
				key: "modelPath",
				label: m.config_field_model,
				kind: "model",
				stage: "tts",
				hint: m.config_hint_tts_model,
			},
			{
				key: "voiceName",
				label: m.config_field_voice,
				kind: "text",
				hint: m.config_hint_voice,
			},
			{
				key: "speed",
				label: m.config_field_speed,
				kind: "slider",
				min: 0.5,
				max: 2,
				step: 0.05,
				unit: "×",
			},
			{
				key: "pitch",
				label: m.config_field_pitch,
				kind: "slider",
				min: -1,
				max: 1,
				step: 0.05,
			},
			{
				key: "silenceScale",
				label: m.config_field_pause_length,
				kind: "slider",
				min: 0,
				max: 2,
				step: 0.05,
			},
			{
				key: "sentenceSoftFlushMinChars",
				label: m.config_field_soft_flush,
				kind: "number",
				unit: "chars",
			},
			{
				key: "sentenceFirstUnitMaxWords",
				label: m.config_field_first_unit,
				kind: "number",
				unit: "words",
			},
			{
				key: "sentenceMediumFlushChars",
				label: m.config_field_medium_flush,
				kind: "number",
				unit: "chars",
			},
			{
				key: "sentenceHardFlushChars",
				label: m.config_field_hard_flush,
				kind: "number",
				unit: "chars",
			},
			{
				key: "sentenceFirstFlushMaxMs",
				label: m.config_field_first_flush_cap,
				kind: "number",
				unit: "ms",
				hint: m.config_hint_first_flush_cap,
			},
			{
				key: "pipelineMaxQueueDepth",
				label: m.config_field_pipeline_depth,
				kind: "number",
				unit: "sentences",
				hint: m.config_hint_pipeline_depth,
			},
			{
				key: "pipelineEagerTtsSentences",
				label: m.config_field_eager_synthesis,
				kind: "number",
				unit: "sentences",
				hint: m.config_hint_eager_synthesis,
			},
			{ key: "language", label: m.config_field_language, kind: "text" },
			{
				key: "maxNumSentences",
				label: m.config_field_sentences_per_chunk,
				kind: "number",
				hint: m.config_hint_sentences_per_chunk,
			},
			{
				key: "streamingEnabled",
				label: m.config_field_stream_while_generating,
				kind: "boolean",
			},
			{ key: "numThreads", label: m.config_field_threads, kind: "number" },
			{
				key: "provider",
				label: m.config_field_compute,
				kind: "select",
				options: PROVIDERS,
			},
			{
				key: "poolWarmWorkers",
				label: m.config_field_warm_workers,
				kind: "number",
			},
			{
				key: "poolExecutionTimeoutMs",
				label: m.config_field_job_timeout,
				kind: "number",
				unit: "ms",
			},
			{
				key: "poolMaxWorkers",
				label: m.config_field_max_workers,
				kind: "number",
				hint: m.config_hint_max_workers_auto,
			},
		],
	},
	{
		id: "llm",
		label: m.config_section_llm,
		icon: "brain",
		group: "engines",
		kind: "fields",
		description: m.config_section_llm_desc,
		fields: [
			{
				key: "engine",
				label: m.config_field_engine,
				kind: "select",
				options: LLM_ENGINES,
			},
			{
				key: "baseUrl",
				label: m.config_field_server_url,
				kind: "text",
				hint: m.config_hint_server_url,
			},
			{
				key: "apiKey",
				label: m.config_field_api_key,
				kind: "text",
				hint: m.config_hint_api_key,
			},
			{
				key: "modelName",
				label: m.config_field_model,
				kind: "model",
				stage: "llm",
				hint: m.config_hint_llm_model,
			},
			{
				key: "reflectionModelName",
				label: m.config_field_reflection_model,
				kind: "model",
				stage: "llm",
				hint: m.config_hint_reflection_model,
			},
			{
				key: "temperature",
				label: m.config_field_creativity,
				kind: "slider",
				min: 0,
				max: 2,
				step: 0.05,
				hint: m.config_hint_creativity,
			},
			{
				key: "contextWindow",
				label: m.config_field_context_window,
				kind: "number",
				unit: "tokens",
			},
			{
				key: "numPredict",
				label: m.config_field_max_reply_length,
				kind: "number",
				unit: "tokens",
			},
			{
				key: "llmConcurrency",
				label: m.config_field_concurrency,
				kind: "number",
			},
			{
				key: "useCompactPrompt",
				label: m.config_field_compact_prompt,
				kind: "boolean",
				hint: m.config_hint_compact_prompt,
			},
			{
				key: "agentPromptMode",
				label: m.config_field_skills_prompt_mode,
				kind: "select",
				options: ["lean", "compact", "full"],
				hint: m.config_hint_skills_prompt_mode,
			},
			{
				key: "skillsRouting",
				label: m.config_field_skills_routing,
				kind: "select",
				options: ["intent-gate", "always-agent"],
				hint: m.config_hint_skills_routing,
			},
			{
				key: "intentModelName",
				label: m.config_field_intent_model,
				kind: "model",
				hint: m.config_hint_intent_model,
			},
			{
				key: "agentMaxSteps",
				label: m.config_field_agent_max_steps,
				kind: "number",
				hint: m.config_hint_agent_max_steps,
			},
		],
	},
	{
		id: "stt",
		label: m.config_section_stt,
		icon: "ear",
		group: "engines",
		kind: "fields",
		description: m.config_section_stt_desc,
		fields: [
			{
				key: "engine",
				label: m.config_field_engine,
				kind: "select",
				options: STT_ENGINES,
			},
			{
				key: "modelPath",
				label: m.config_field_model,
				kind: "model",
				stage: "stt",
				hint: m.config_hint_stt_model,
			},
			{ key: "language", label: m.config_field_language, kind: "text" },
			{
				key: "enableEndpoint",
				label: m.config_field_endpoint_detection,
				kind: "boolean",
				hint: m.config_hint_endpoint_detection,
			},
			{
				key: "decodePaddingMs",
				label: m.config_field_decode_padding,
				kind: "number",
				unit: "ms",
			},
			{ key: "numThreads", label: m.config_field_threads, kind: "number" },
			{
				key: "provider",
				label: m.config_field_compute,
				kind: "select",
				options: PROVIDERS,
			},
			{
				key: "poolWarmWorkers",
				label: m.config_field_warm_workers,
				kind: "number",
			},
			{
				key: "poolExecutionTimeoutMs",
				label: m.config_field_job_timeout,
				kind: "number",
				unit: "ms",
			},
			{
				key: "poolMaxWorkers",
				label: m.config_field_max_workers,
				kind: "number",
				hint: m.config_hint_max_workers_auto,
			},
		],
	},
	{
		id: "wakeWord",
		label: m.config_section_wakeword,
		icon: "mic",
		group: "engines",
		kind: "fields",
		description: m.config_section_wakeword_desc,
		fields: [
			{
				key: "engine",
				label: m.config_field_engine,
				kind: "select",
				options: WAKE_WORD_ENGINES,
			},
			{
				key: "wakeWord",
				label: m.config_field_keyword,
				kind: "text",
				hint: m.config_hint_keyword,
			},
			{
				key: "sensitivity",
				label: m.config_field_keyword_boost,
				kind: "slider",
				min: 0.5,
				max: 3,
				step: 0.1,
				hint: m.config_hint_keyword_boost,
			},
			{
				key: "threshold",
				label: m.config_field_detection_threshold,
				kind: "slider",
				min: 0.05,
				max: 1,
				step: 0.05,
				hint: m.config_hint_detection_threshold,
			},
			{
				key: "cooldown",
				label: m.config_field_cooldown,
				kind: "number",
				unit: "s",
			},
			{ key: "numThreads", label: m.config_field_threads, kind: "number" },
			{
				key: "provider",
				label: m.config_field_provider,
				kind: "select",
				options: PROVIDERS,
			},
			{
				key: "customModelPath",
				label: m.config_field_wake_model,
				kind: "model",
				stage: "wakeWord",
			},
			{
				key: "vadModelPath",
				label: m.config_field_vad_model,
				kind: "model",
				stage: "vad",
			},
			{
				key: "vadThreshold",
				label: m.config_field_vad_threshold,
				kind: "slider",
				min: 0.1,
				max: 0.9,
				step: 0.05,
			},
			{
				key: "vadMinSilenceS",
				label: m.config_field_min_silence,
				kind: "number",
				unit: "s",
				hint: m.config_hint_min_silence,
			},
			{
				key: "vadEndOfSpeechMs",
				label: m.config_field_end_of_speech,
				kind: "number",
				unit: "ms",
				hint: m.config_hint_end_of_speech,
			},
			{
				key: "sampleRate",
				label: m.config_field_sample_rate,
				kind: "number",
				unit: "Hz",
			},
			{ key: "channels", label: m.config_field_channels, kind: "number" },
			{
				key: "maxRecordingMs",
				label: m.config_field_max_recording,
				kind: "number",
				unit: "ms",
			},
			{
				key: "followUpWindowMs",
				label: m.config_field_follow_up_window,
				kind: "number",
				unit: "ms",
				hint: m.config_hint_follow_up_window,
			},
			{
				key: "bargeInEnabled",
				label: m.config_field_barge_in,
				kind: "boolean",
				hint: m.config_hint_barge_in,
			},
			{
				key: "speculativeSilenceMs",
				label: m.config_field_speculative_commit,
				kind: "number",
				unit: "ms",
				hint: m.config_hint_speculative_commit,
			},
			{
				key: "followUpLeadPadMs",
				label: m.config_field_follow_up_lead_pad,
				kind: "number",
				unit: "ms",
				hint: m.config_hint_follow_up_lead_pad,
			},
		],
	},
	{
		id: "playback",
		label: m.config_section_playback,
		icon: "speaker",
		group: "engines",
		kind: "fields",
		description: m.config_section_playback_desc,
		fields: [
			{
				key: "engine",
				label: m.config_field_engine,
				kind: "select",
				options: PLAYBACK_ENGINES,
			},
			{
				key: "volume",
				label: m.config_field_volume,
				kind: "slider",
				min: 0,
				max: 100,
				step: 1,
			},
			{
				key: "streamingEnabled",
				label: m.config_field_stream_audio,
				kind: "boolean",
			},
			{
				key: "truncationReplayEnabled",
				label: m.config_field_truncation_replay,
				kind: "boolean",
				hint: m.config_hint_truncation_replay,
			},
			{
				key: "truncationReplayThresholdMs",
				label: m.config_field_truncation_replay_threshold,
				kind: "slider",
				min: 0,
				max: 3000,
				step: 50,
				hint: m.config_hint_truncation_replay_threshold,
			},
			{
				key: "outputDevice",
				label: m.config_field_output_device,
				kind: "text",
			},
			{
				key: "feedbackSoundsEnabled",
				label: m.config_field_feedback_sounds,
				kind: "boolean",
				hint: m.config_hint_feedback_sounds,
			},
			{
				key: "ackSoundEnabled",
				label: m.config_field_ack_sound,
				kind: "boolean",
			},
			{
				key: "ackSoundPath",
				label: m.config_field_ack_sound_path,
				kind: "text",
			},
			{
				key: "errorSoundEnabled",
				label: m.config_field_error_sound,
				kind: "boolean",
			},
			{
				key: "errorSoundPath",
				label: m.config_field_error_sound_path,
				kind: "text",
			},
			{
				key: "doneSoundEnabled",
				label: m.config_field_done_sound,
				kind: "boolean",
			},
			{
				key: "doneSoundPath",
				label: m.config_field_done_sound_path,
				kind: "text",
			},
			{
				key: "thinkingSoundEnabled",
				label: m.config_field_thinking_sound,
				kind: "boolean",
			},
			{
				key: "thinkingSoundPath",
				label: m.config_field_thinking_sound_path,
				kind: "text",
			},
		],
	},
	{
		id: "capabilities",
		label: m.config_section_capabilities,
		icon: "toggle",
		group: "behavior",
		kind: "fields",
		description: m.config_section_capabilities_desc,
		fields: [
			{
				key: "wakeword",
				label: m.enum_capability_wakeword,
				kind: "boolean",
				hint: m.config_hint_cap_wakeword,
			},
			{
				key: "record",
				label: m.enum_capability_record,
				kind: "boolean",
				hint: m.config_hint_cap_record,
			},
			{ key: "stt", label: m.enum_capability_stt, kind: "boolean" },
			{ key: "llm", label: m.enum_capability_llm, kind: "boolean" },
			{ key: "tts", label: m.enum_capability_tts, kind: "boolean" },
			{ key: "playback", label: m.enum_capability_playback, kind: "boolean" },
			{
				key: "intentDetection",
				label: m.enum_capability_intent_detection,
				kind: "boolean",
			},
			{
				key: "intentExecution",
				label: m.enum_capability_intent_execution,
				kind: "boolean",
			},
			{
				key: "promptGeneration",
				label: m.enum_capability_prompt_generation,
				kind: "boolean",
			},
		],
	},
	{
		id: "modules",
		label: m.config_section_modules,
		icon: "boxes",
		group: "behavior",
		kind: "fields",
		description: m.config_section_modules_desc,
		fields: [
			{
				key: "emotionEngine",
				label: m.mind_module_emotion_engine,
				kind: "boolean",
				hint: m.mind_module_emotion_engine_hint,
			},
			{
				key: "emotionCapture",
				label: m.config_field_emotion_capture,
				kind: "boolean",
				hint: m.config_hint_emotion_capture,
			},
			{
				key: "memoryEngine",
				label: m.mind_module_memory_engine,
				kind: "boolean",
				hint: m.mind_module_memory_engine_hint,
			},
			{
				key: "factCapture",
				label: m.config_field_fact_capture,
				kind: "boolean",
			},
			{ key: "factRecall", label: m.config_field_fact_recall, kind: "boolean" },
			{
				key: "collectiveMind",
				label: m.mind_module_collective_mind,
				kind: "boolean",
				hint: m.mind_module_collective_mind_hint,
			},
			{
				key: "narrativeEngine",
				label: m.mind_module_narrative_engine,
				kind: "boolean",
			},
			{
				key: "identityEngine",
				label: m.mind_module_identity_engine,
				kind: "boolean",
				hint: m.mind_module_identity_engine_hint,
			},
			{
				key: "remoteAccessEngine",
				label: m.mind_module_remote_access,
				kind: "boolean",
				hint: m.mind_module_remote_access_hint,
			},
			{
				key: "skillsEngine",
				label: m.config_field_skills_tools,
				kind: "boolean",
				hint: m.config_hint_skills_tools,
			},
			{
				key: "reflectionOnlyWhenIdle",
				label: m.config_field_reflect_only_idle,
				kind: "boolean",
			},
			{
				key: "reflectionConcurrency",
				label: m.config_field_reflection_concurrency,
				kind: "number",
			},
			{
				key: "reflectionYieldToVoice",
				label: m.config_field_yield_to_voice,
				kind: "boolean",
				hint: m.config_hint_yield_to_voice,
			},
		],
	},
	{
		id: "skills",
		label: m.config_section_skills,
		icon: "package",
		group: "behavior",
		kind: "skill",
		description: m.config_section_skills_desc,
		fields: [],
	},
	{
		id: "mqttLocal",
		label: m.config_section_mqtt,
		icon: "network",
		group: "system",
		kind: "fields",
		description: m.config_section_mqtt_desc,
		fields: [
			{ key: "host", label: m.config_field_host, kind: "text" },
			{ key: "port", label: m.config_field_port, kind: "number" },
			{
				key: "protocol",
				label: m.config_field_protocol,
				kind: "select",
				options: MQTT_PROTOCOLS,
			},
			{ key: "username", label: m.config_field_username, kind: "text" },
			{ key: "password", label: m.config_field_password, kind: "text" },
			{ key: "qos", label: m.config_field_qos, kind: "number" },
			{ key: "topicRoot", label: m.config_field_topic_root, kind: "text" },
		],
	},
	{
		id: "advanced",
		label: m.config_section_advanced,
		icon: "sliders",
		group: "system",
		kind: "fields",
		source: "domia",
		description: m.config_section_advanced_desc,
		fields: [
			{
				key: "sessionIdTimeoutMs",
				label: m.config_field_session_timeout,
				kind: "number",
				unit: "ms",
			},
			{
				key: "memoryWindowTurns",
				label: m.config_field_memory_window,
				kind: "number",
				unit: "turns",
			},
			{
				key: "memoryMaxAgeMs",
				label: m.config_field_memory_max_age,
				kind: "number",
				unit: "ms",
			},
			{
				key: "maxConcurrentVoiceReplies",
				label: m.config_field_max_concurrent_replies,
				kind: "number",
			},
			{
				key: "maxQueuedVoiceReplies",
				label: m.config_field_max_queued_replies,
				kind: "number",
			},
			{
				key: "voiceQueueTimeoutMs",
				label: m.config_field_voice_queue_timeout,
				kind: "number",
				unit: "ms",
			},
			{
				key: "ownConfigTtlMs",
				label: m.config_field_config_cache_ttl,
				kind: "number",
				unit: "ms",
			},
			{
				key: "warmupOnBoot",
				label: m.config_field_warmup_on_boot,
				kind: "boolean",
				hint: m.config_hint_warmup_on_boot,
			},
			{
				key: "grpcUnaryDeadlineMs",
				label: m.config_field_grpc_unary_deadline,
				kind: "number",
				unit: "ms",
			},
			{
				key: "grpcStreamIdleTimeoutMs",
				label: m.config_field_grpc_stream_idle,
				kind: "number",
				unit: "ms",
			},
			{
				key: "grpcStreamDeadlineMs",
				label: m.config_field_grpc_stream_deadline,
				kind: "number",
				unit: "ms",
			},
			{
				key: "peerStaleAfterMs",
				label: m.config_field_peer_stale_after,
				kind: "number",
				unit: "ms",
				hint: m.config_hint_peer_stale_after,
			},
		],
	},
	{
		id: "health",
		label: m.config_section_health,
		icon: "stethoscope",
		group: "diagnostics",
		kind: "diagnostics",
		description: m.config_section_health_desc,
		fields: [],
	},
	{
		id: "models",
		label: m.config_section_models,
		icon: "package",
		group: "diagnostics",
		kind: "models",
		description: m.config_section_models_desc,
		fields: [],
	},
]

export const SECTION_GROUPS = [
	"personality",
	"engines",
	"behavior",
	"system",
	"diagnostics",
] as const

export const SECTION_GROUP_LABELS: Record<
	(typeof SECTION_GROUPS)[number],
	() => string
> = {
	personality: m.config_group_personality,
	engines: m.config_group_engines,
	behavior: m.config_group_behavior,
	system: m.config_group_system,
	diagnostics: m.config_group_diagnostics,
}

export const ARCHETYPE_PRESETS: ArchetypePreset[] = [
	{
		id: "standalone",
		label: m.config_archetype_standalone,
		description: m.config_archetype_standalone_desc,
		capabilities: {
			wakeword: true,
			record: true,
			stt: true,
			llm: true,
			tts: true,
			playback: true,
			intentDetection: true,
			intentExecution: true,
			promptGeneration: true,
		},
	},
	{
		id: "thin-client",
		label: m.config_archetype_thin_client,
		description: m.config_archetype_thin_client_desc,
		capabilities: {
			wakeword: true,
			record: true,
			stt: false,
			llm: false,
			tts: false,
			playback: true,
			intentDetection: false,
			intentExecution: false,
			promptGeneration: false,
		},
	},
	{
		id: "inference-hub",
		label: m.config_archetype_inference_hub,
		description: m.config_archetype_inference_hub_desc,
		capabilities: {
			wakeword: false,
			record: false,
			stt: true,
			llm: true,
			tts: true,
			playback: false,
			intentDetection: true,
			intentExecution: true,
			promptGeneration: true,
		},
	},
]
