import {
	CHARACTER_ENUM_FIELDS,
	CHARACTER_TAG_FIELDS,
	EMOTION_FIELDS,
} from "@/constants/mind"
import type {
	ArchetypePreset,
	ConfigField,
	ConfigSectionDef,
} from "@/types/config"

const STT_ENGINES = ["WHISPER", "MOONSHINE", "ZIPFORMER"] as const
const LLM_ENGINES = ["OLLAMA", "LLAMA_CPP"] as const
const TTS_ENGINES = ["KOKORO"] as const
const WAKE_WORD_ENGINES = ["KWS"] as const
const PLAYBACK_ENGINES = ["SOX", "PLAY-SOUND"] as const
const MQTT_PROTOCOLS = ["mqtt", "mqtts", "ws", "wss"] as const
const PROVIDERS = ["cpu", "cuda", "coreml"] as const

const PERSONA_FIELDS: ConfigField[] = [
	{
		key: "name",
		label: "Character name",
		kind: "text",
		hint: "How the Domia refers to itself.",
	},
	...CHARACTER_ENUM_FIELDS.map(
		(f): ConfigField => ({
			key: f.key,
			label: f.label,
			kind: "select",
			options: f.values,
		}),
	),
	{ key: "language", label: "Primary language", kind: "text" },
	{ key: "culturalBackground", label: "Cultural background", kind: "text" },
	...CHARACTER_TAG_FIELDS.map(
		(f): ConfigField => ({ key: f.key, label: f.label, kind: "tags" }),
	),
]

const EMOTION_RADAR_FIELDS: ConfigField[] = EMOTION_FIELDS.map(
	(f): ConfigField => ({
		key: f.key,
		label: f.label,
		kind: "slider",
		min: -1,
		max: 1,
		step: 0.05,
	}),
)

export const CONFIG_SECTIONS: ConfigSectionDef[] = [
	{
		id: "identity",
		label: "Identity",
		icon: "identity",
		group: "Personality",
		kind: "fields",
		source: "domia",
		description:
			"This Domia's name on the network — how it shows up everywhere in the console.",
		fields: [
			{
				key: "name",
				label: "Domia name",
				kind: "text",
				hint: "A human name for this device, e.g. Kitchen or Living Room.",
			},
		],
	},
	{
		id: "character",
		label: "Personality",
		icon: "user",
		group: "Personality",
		kind: "fields",
		description: "Who this Domia is — character and the way it talks.",
		fields: PERSONA_FIELDS,
	},
	{
		id: "emotion",
		label: "Mood",
		icon: "heart",
		group: "Personality",
		kind: "radar",
		description:
			"Baseline mood it starts each conversation from. Each axis runs −1 to 1 — drag the radar or use the sliders.",
		fields: EMOTION_RADAR_FIELDS,
	},
	{
		id: "tts",
		label: "Voice",
		icon: "audio",
		group: "Engines & models",
		kind: "fields",
		description: "Text-to-speech engine, voice and delivery.",
		fields: [
			{ key: "engine", label: "Engine", kind: "select", options: TTS_ENGINES },
			{
				key: "modelPath",
				label: "Model",
				kind: "model",
				stage: "tts",
				hint: "Installed TTS model directory.",
			},
			{
				key: "voiceName",
				label: "Voice",
				kind: "text",
				hint: "Voice within the model, e.g. af_heart.",
			},
			{
				key: "speed",
				label: "Speed",
				kind: "slider",
				min: 0.5,
				max: 2,
				step: 0.05,
				unit: "×",
			},
			{
				key: "pitch",
				label: "Pitch",
				kind: "slider",
				min: -1,
				max: 1,
				step: 0.05,
			},
			{
				key: "silenceScale",
				label: "Pause length",
				kind: "slider",
				min: 0,
				max: 2,
				step: 0.05,
			},
			{ key: "language", label: "Language", kind: "text" },
			{
				key: "maxNumSentences",
				label: "Sentences per chunk",
				kind: "number",
				hint: "Lower = faster first audio.",
			},
			{
				key: "streamingEnabled",
				label: "Stream while generating",
				kind: "boolean",
			},
			{ key: "numThreads", label: "Threads", kind: "number" },
			{ key: "provider", label: "Compute", kind: "select", options: PROVIDERS },
			{ key: "poolWarmWorkers", label: "Warm workers", kind: "number" },
			{
				key: "poolMaxWorkers",
				label: "Max workers",
				kind: "number",
				hint: "0 = auto from cores.",
			},
		],
	},
	{
		id: "llm",
		label: "Brain",
		icon: "brain",
		group: "Engines & models",
		kind: "fields",
		description: "The language model that thinks and replies.",
		fields: [
			{ key: "engine", label: "Engine", kind: "select", options: LLM_ENGINES },
			{
				key: "modelName",
				label: "Model",
				kind: "model",
				stage: "llm",
				hint: "Installed Ollama model.",
			},
			{
				key: "temperature",
				label: "Creativity",
				kind: "slider",
				min: 0,
				max: 2,
				step: 0.05,
				hint: "Higher = more varied.",
			},
			{
				key: "contextWindow",
				label: "Context window",
				kind: "number",
				unit: "tokens",
			},
			{
				key: "numPredict",
				label: "Max reply length",
				kind: "number",
				unit: "tokens",
			},
			{ key: "llmConcurrency", label: "Concurrency", kind: "number" },
			{
				key: "useCompactPrompt",
				label: "Compact prompt",
				kind: "boolean",
				hint: "Smaller prompt, faster, less nuance.",
			},
		],
	},
	{
		id: "stt",
		label: "Hearing",
		icon: "ear",
		group: "Engines & models",
		kind: "fields",
		description: "Speech-to-text — how it transcribes what it hears.",
		fields: [
			{ key: "engine", label: "Engine", kind: "select", options: STT_ENGINES },
			{
				key: "modelPath",
				label: "Model",
				kind: "model",
				stage: "stt",
				hint: "Installed STT model directory.",
			},
			{ key: "language", label: "Language", kind: "text" },
			{
				key: "enableEndpoint",
				label: "Endpoint detection",
				kind: "boolean",
				hint: "Auto-detect end of speech.",
			},
			{
				key: "decodePaddingMs",
				label: "Decode padding",
				kind: "number",
				unit: "ms",
			},
			{ key: "numThreads", label: "Threads", kind: "number" },
			{ key: "provider", label: "Compute", kind: "select", options: PROVIDERS },
			{ key: "poolWarmWorkers", label: "Warm workers", kind: "number" },
			{
				key: "poolMaxWorkers",
				label: "Max workers",
				kind: "number",
				hint: "0 = auto from cores.",
			},
		],
	},
	{
		id: "wakeWord",
		label: "Wake & audio",
		icon: "mic",
		group: "Engines & models",
		kind: "fields",
		description: "Wake word, microphone capture and voice activity.",
		fields: [
			{
				key: "engine",
				label: "Engine",
				kind: "select",
				options: WAKE_WORD_ENGINES,
			},
			{
				key: "wakeWord",
				label: "Keyword",
				kind: "text",
				hint: "What wakes it, e.g. computer.",
			},
			{
				key: "sensitivity",
				label: "Sensitivity",
				kind: "slider",
				min: 0,
				max: 1,
				step: 0.05,
			},
			{
				key: "threshold",
				label: "Threshold",
				kind: "slider",
				min: 0,
				max: 1,
				step: 0.05,
			},
			{ key: "cooldown", label: "Cooldown", kind: "number", unit: "ms" },
			{
				key: "customModelPath",
				label: "Wake model",
				kind: "model",
				stage: "wakeWord",
			},
			{ key: "vadModelPath", label: "VAD model", kind: "model", stage: "vad" },
			{ key: "sampleRate", label: "Sample rate", kind: "number", unit: "Hz" },
			{ key: "channels", label: "Channels", kind: "number" },
			{
				key: "maxRecordingMs",
				label: "Max recording",
				kind: "number",
				unit: "ms",
			},
		],
	},
	{
		id: "playback",
		label: "Playback",
		icon: "speaker",
		group: "Engines & models",
		kind: "fields",
		description: "How synthesized audio is played back.",
		fields: [
			{
				key: "engine",
				label: "Engine",
				kind: "select",
				options: PLAYBACK_ENGINES,
			},
			{
				key: "volume",
				label: "Volume",
				kind: "slider",
				min: 0,
				max: 100,
				step: 1,
			},
			{ key: "streamingEnabled", label: "Stream audio", kind: "boolean" },
			{ key: "outputDevice", label: "Output device", kind: "text" },
		],
	},
	{
		id: "capabilities",
		label: "Capabilities",
		icon: "toggle",
		group: "Behavior",
		kind: "fields",
		description: "Which parts of the pipeline this Domia runs locally.",
		fields: [
			{
				key: "wakeword",
				label: "Wake word",
				kind: "boolean",
				hint: "Listen for the keyword.",
			},
			{
				key: "record",
				label: "Record",
				kind: "boolean",
				hint: "Capture microphone audio.",
			},
			{ key: "stt", label: "Speech to text", kind: "boolean" },
			{ key: "llm", label: "Language model", kind: "boolean" },
			{ key: "tts", label: "Text to speech", kind: "boolean" },
			{ key: "playback", label: "Playback", kind: "boolean" },
			{ key: "intentDetection", label: "Intent detection", kind: "boolean" },
			{ key: "intentExecution", label: "Intent execution", kind: "boolean" },
			{ key: "promptGeneration", label: "Prompt generation", kind: "boolean" },
		],
	},
	{
		id: "modules",
		label: "Behavior",
		icon: "boxes",
		group: "Behavior",
		kind: "fields",
		description: "Memory, emotion, identity and other cognitive modules.",
		fields: [
			{
				key: "emotionEngine",
				label: "Emotion engine",
				kind: "boolean",
				hint: "Apply a mood to replies.",
			},
			{
				key: "emotionCapture",
				label: "Emotion capture",
				kind: "boolean",
				hint: "Learn mood from interactions.",
			},
			{
				key: "memoryEngine",
				label: "Memory engine",
				kind: "boolean",
				hint: "Recall prior turns and facts.",
			},
			{ key: "factCapture", label: "Fact capture", kind: "boolean" },
			{ key: "factRecall", label: "Fact recall", kind: "boolean" },
			{
				key: "collectiveMind",
				label: "Collective mind",
				kind: "boolean",
				hint: "Share knowledge across Domias.",
			},
			{ key: "narrativeEngine", label: "Narrative engine", kind: "boolean" },
			{
				key: "identityEngine",
				label: "Identity engine",
				kind: "boolean",
				hint: "Recognize who is speaking.",
			},
			{
				key: "remoteAccessEngine",
				label: "Remote access",
				kind: "boolean",
				hint: "Delegate work to peers.",
			},
			{
				key: "reflectionOnlyWhenIdle",
				label: "Reflect only when idle",
				kind: "boolean",
			},
			{
				key: "reflectionConcurrency",
				label: "Reflection concurrency",
				kind: "number",
			},
		],
	},
	{
		id: "mqttLocal",
		label: "Network",
		icon: "network",
		group: "System",
		kind: "fields",
		description: "Local MQTT broker for discovery and heartbeat.",
		fields: [
			{ key: "host", label: "Host", kind: "text" },
			{ key: "port", label: "Port", kind: "number" },
			{
				key: "protocol",
				label: "Protocol",
				kind: "select",
				options: MQTT_PROTOCOLS,
			},
			{ key: "username", label: "Username", kind: "text" },
			{ key: "password", label: "Password", kind: "text" },
			{ key: "qos", label: "QoS", kind: "number" },
			{ key: "topicRoot", label: "Topic root", kind: "text" },
		],
	},
	{
		id: "advanced",
		label: "Advanced",
		icon: "sliders",
		group: "System",
		kind: "fields",
		source: "domia",
		description: "Session, memory window and concurrency tuning.",
		fields: [
			{
				key: "sessionIdTimeoutMs",
				label: "Session timeout",
				kind: "number",
				unit: "ms",
			},
			{
				key: "memoryWindowTurns",
				label: "Memory window",
				kind: "number",
				unit: "turns",
			},
			{
				key: "memoryMaxAgeMs",
				label: "Memory max age",
				kind: "number",
				unit: "ms",
			},
			{
				key: "maxConcurrentVoiceReplies",
				label: "Max concurrent replies",
				kind: "number",
			},
			{
				key: "maxQueuedVoiceReplies",
				label: "Max queued replies",
				kind: "number",
			},
			{
				key: "voiceQueueTimeoutMs",
				label: "Voice queue timeout",
				kind: "number",
				unit: "ms",
			},
			{
				key: "ownConfigTtlMs",
				label: "Config cache TTL",
				kind: "number",
				unit: "ms",
			},
		],
	},
	{
		id: "health",
		label: "Diagnostics",
		icon: "stethoscope",
		group: "Diagnostics",
		kind: "diagnostics",
		description: "Configured engines vs what is actually installed.",
		fields: [],
	},
	{
		id: "models",
		label: "Models",
		icon: "package",
		group: "Diagnostics",
		kind: "models",
		description: "Install and inspect models for every stage.",
		fields: [],
	},
]

export const SECTION_GROUPS = [
	"Personality",
	"Engines & models",
	"Behavior",
	"System",
	"Diagnostics",
] as const

export const ARCHETYPE_PRESETS: ArchetypePreset[] = [
	{
		id: "full-hub",
		label: "Full hub",
		description: "Runs the whole pipeline locally and can serve peers.",
		capabilities: {
			wakeword: true,
			record: true,
			stt: true,
			llm: true,
			tts: true,
			playback: true,
			intentDetection: true,
			intentExecution: true,
			promptGeneration: true,
		},
	},
	{
		id: "thin-client",
		label: "Thin client",
		description: "Wake word + audio only; delegates STT/LLM/TTS to a hub.",
		capabilities: {
			wakeword: true,
			record: true,
			stt: false,
			llm: false,
			tts: false,
			playback: true,
			intentDetection: false,
			intentExecution: false,
			promptGeneration: false,
		},
	},
	{
		id: "headless-brain",
		label: "Headless brain",
		description: "Processing node — STT/LLM/TTS, no mic or speaker.",
		capabilities: {
			wakeword: false,
			record: false,
			stt: true,
			llm: true,
			tts: true,
			playback: false,
			intentDetection: true,
			intentExecution: true,
			promptGeneration: true,
		},
	},
]
