import { m } from "@/paraglide/messages"

const KNOWN_ERRORS: Record<string, () => string> = {
	"Empty response": m.err_empty_response,
	"request failed": m.err_request_failed,
	"Domia not found": m.err_domia_not_found,
	"Unknown preset": m.err_unknown_preset,
	"Unsupported image type": m.err_unsupported_image,
	"Empty image": m.err_empty_image,
	"Image too large (max 2MB)": m.err_image_too_large,
	"This Domia has no reachable address": m.err_domia_unreachable,
	"Could not apply changes": m.err_apply_changes,
	"Could not load diagnostics": m.err_load_diagnostics,
	"Could not restart Domia": m.err_restart_domia,
	"No audio to send": m.err_no_audio,
	"Message is empty": m.err_message_empty,
	"Send failed": m.err_send_failed,
	"Could not load history": m.err_load_history,
	"Could not load fleet graph": m.err_load_fleet_graph,
	"Failed to save label": m.err_save_label,
	"Failed to grade": m.err_grade,
	"Could not load knowledge": m.err_load_knowledge,
	"Could not save entry": m.err_save_entry,
	"Could not delete entry": m.err_delete_entry,
	"This node has no reachable address": m.err_node_unreachable,
	"Could not load topology": m.err_load_topology,
	"Could not load models": m.err_load_models,
	"Could not start install": m.err_start_install,
	"Could not read job status": m.err_job_status,
	"Could not list identities": m.err_list_identities,
	"Could not create identity": m.err_create_identity,
	"Could not remove identity": m.err_remove_identity,
	"Announce failed": m.err_announce_failed,
	"Host has no reachable address": m.err_host_unreachable,
	"Stop failed": m.err_stop_failed,
	"Intercom failed": m.err_intercom_failed,
	"Source interaction not found": m.err_source_not_found,
	"Target node has no reachable address": m.err_target_unreachable,
	"No input audio archived for voice re-run": m.err_no_archived_audio,
	"No input text to re-run": m.err_no_input_text,
	"Run failed": m.err_run_failed,
	"Discovery failed": m.err_discovery_failed,
	"Could not list satellites": m.err_list_satellites,
	"Could not bind satellite": m.err_bind_satellite,
	"Could not unbind satellite": m.err_unbind_satellite,
	"Could not set wake words": m.err_set_wake_words,
	"Could not set value": m.err_set_value,
	"Could not set follow-up": m.err_set_follow_up,
	"Could not set volume": m.err_set_volume,
	"Could not test speaker": m.err_test_speaker,
	"System templates can't be deleted": m.err_system_template_delete,
	"System templates are read-only — clone instead":
		m.err_system_template_readonly,
	"Template not found": m.err_template_not_found,
	"name already in use": m.err_name_in_use,
}

export const errText = (error: string | null | undefined): string => {
	if (!error) return m.err_empty_response()
	return KNOWN_ERRORS[error]?.() ?? error
}
